In [2]:
import tensorflow as tf


In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
voc_size=10000

In [9]:

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8924, 8282, 1767, 2870], [8924, 8282, 1767, 5013], [8924, 9426, 1767, 8606], [4602, 3543, 8617, 3265, 8455], [4602, 3543, 8617, 3265, 4078], [1118, 8924, 2796, 1767, 1468], [2802, 1965, 8295, 3265]]


In [10]:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8924 8282 1767 2870]
 [   0    0    0    0 8924 8282 1767 5013]
 [   0    0    0    0 8924 9426 1767 8606]
 [   0    0    0 4602 3543 8617 3265 8455]
 [   0    0    0 4602 3543 8617 3265 4078]
 [   0    0    0 1118 8924 2796 1767 1468]
 [   0    0    0    0 2802 1965 8295 3265]]


In [13]:
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

[[[-2.75344383e-02 -1.19675025e-02  1.52295567e-02 -2.68714558e-02
    1.42347701e-02  3.50136422e-02  3.52325477e-02 -4.60901745e-02
   -2.41858251e-02 -9.36914235e-04]
  [-2.75344383e-02 -1.19675025e-02  1.52295567e-02 -2.68714558e-02
    1.42347701e-02  3.50136422e-02  3.52325477e-02 -4.60901745e-02
   -2.41858251e-02 -9.36914235e-04]
  [-2.75344383e-02 -1.19675025e-02  1.52295567e-02 -2.68714558e-02
    1.42347701e-02  3.50136422e-02  3.52325477e-02 -4.60901745e-02
   -2.41858251e-02 -9.36914235e-04]
  [-2.75344383e-02 -1.19675025e-02  1.52295567e-02 -2.68714558e-02
    1.42347701e-02  3.50136422e-02  3.52325477e-02 -4.60901745e-02
   -2.41858251e-02 -9.36914235e-04]
  [-3.36443670e-02 -2.23607551e-02  2.07925960e-03 -2.31147539e-02
   -3.76199372e-02  2.16759704e-02 -9.85919312e-03  4.70801331e-02
    2.94371583e-02  3.84751819e-02]
  [-4.46461812e-02  2.26900727e-03 -2.76159886e-02  3.06066386e-02
   -3.54833603e-02  3.54457609e-02  1.75616033e-02 -2.70925462e-04
   -4.69676368e-

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 8924, 8282, 1767, 2870])

In [18]:

print(model.predict(embedded_docs)[0])

[[-0.02753444 -0.0119675   0.01522956 -0.02687146  0.01423477  0.03501364
   0.03523255 -0.04609017 -0.02418583 -0.00093691]
 [-0.02753444 -0.0119675   0.01522956 -0.02687146  0.01423477  0.03501364
   0.03523255 -0.04609017 -0.02418583 -0.00093691]
 [-0.02753444 -0.0119675   0.01522956 -0.02687146  0.01423477  0.03501364
   0.03523255 -0.04609017 -0.02418583 -0.00093691]
 [-0.02753444 -0.0119675   0.01522956 -0.02687146  0.01423477  0.03501364
   0.03523255 -0.04609017 -0.02418583 -0.00093691]
 [-0.03364437 -0.02236076  0.00207926 -0.02311475 -0.03761994  0.02167597
  -0.00985919  0.04708013  0.02943716  0.03847518]
 [-0.04464618  0.00226901 -0.02761599  0.03060664 -0.03548336  0.03544576
   0.0175616  -0.00027093 -0.04696764 -0.00362306]
 [ 0.03976578  0.00803434 -0.02461963 -0.03915042  0.03717358  0.01175744
   0.03413938 -0.01064413 -0.00986253  0.01422526]
 [ 0.00010413  0.00379374 -0.02305377  0.01888892 -0.04882512 -0.00373676
  -0.02248844 -0.01332737 -0.00767193  0.01888965]]